### ISSUE TITLE
Problem when installing

### ISSUE THREAD

**Issue by gelinger777** [amantinetti/laravel-influxdb2#1]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: influxdata/influxdb-client-php[dev-master, 1.9.0].
    - Can only install one of: influxdata/influxdb-client-php[dev-master, 1.9.0].
    - amantinetti/laravel-influxdb2 0.0.1 requires influxdata/influxdb-client-php dev-master -> satisfiable by influxdata/influxdb-client-php[dev-master].
    - Installation request for amantinetti/laravel-influxdb2 ^0.0.1 -> satisfiable by amantinetti/laravel-influxdb2[0.0.1].
    - Installation request for influxdata/influxdb-client-php (installed at 1.9.0) -> satisfiable by influxdata/influxdb-client-php[1.9.0].

**Comment by amantinetti** [comment]
Is fixed in 0.0.2 Version
